name: data_layer_flutter
description: "A new Flutter package project."
version: 0.0.2
homepage:

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^7.0.0
  data_layer: 0.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

dependency_overrides:
  data_layer:
    path: ../data_layer
