name: data_layer_flutter
description: Provides Flutter-specific bindings for pkg:data_layer.
version: 0.0.2
repository: https://github.com/craiglabenz/dash_data_layer

topics:
  - caching
  - persistence
  - data-layer

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^7.0.0
  data_layer: ^0.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

# dependency_overrides:
#   data_layer:
#     path: ../data_layer
