include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: true
    omit_local_variable_types: false
    document_ignores: true

analyzer:
  errors:
    todo: ignore
    document_ignores: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

formatter:
  trailing_commas: preserve
